kind = "mobile"
previewPath = "/"
title = "Rang Roop Badal"
version = "1.0.0"
id = "artifacts/rang-roop-badal"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22902

[services.development]
run = "pnpm --filter @workspace/rang-roop-badal run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rang-roop-badal", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/rang-roop-badal", "run", "serve" ]

[services.env]
PORT = "22902"
BASE_PATH = "/"
