/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/achievements` | `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/character-select` | `/character-select`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/daily-reward` | `/daily-reward`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/game-over` | `/game-over`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/game` | `/game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/snake-shift` | `/snake-shift`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/achievements` | `/achievements`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/character-select` | `/character-select`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/daily-reward` | `/daily-reward`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/game-over` | `/game-over`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/game` | `/game`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/shop` | `/shop`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/snake-shift` | `/snake-shift`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/achievements${`?${string}` | `#${string}` | ''}` | `/achievements${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/character-select${`?${string}` | `#${string}` | ''}` | `/character-select${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/daily-reward${`?${string}` | `#${string}` | ''}` | `/daily-reward${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/game-over${`?${string}` | `#${string}` | ''}` | `/game-over${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/game${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/shop${`?${string}` | `#${string}` | ''}` | `/shop${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/snake-shift${`?${string}` | `#${string}` | ''}` | `/snake-shift${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/achievements` | `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/character-select` | `/character-select`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/daily-reward` | `/daily-reward`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/game-over` | `/game-over`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/game` | `/game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/snake-shift` | `/snake-shift`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
